<?php
$fis_data = array(
    'assets_url' => '/static/smarty_demo',
    'base_url' => '/smarty_demo/page',
    "user_info" => array(
        "name" => '菠萝菠萝蜜',
        "avatar" => 'https://img.lanjinger.com/user_pic/12550_0DBDEBEFDAB3FDF11F120ADBB99D3E8F.@!face-big',
    ),
    "page_name" => "通知公告",

    'data' => array(
        'title' => 'fis3-smarty demo',
        'index' => 2,
        'data_yesterday' => array(
            "date" => "2017-08-20",
            "paid_amount" => 50,
            "welth_order_paid_amount" => 50,
            "welth_order_paid_count" => 1,
            "welth_order_unpaid_count" => 0,
            "welth_order_completion_rate" => 1,
            "vip_order_paid_amount" => 0.00,
            "vip_order_paid_count" => 0,
            "vip_order_unpaid_count" => 0,
            "vip_order_completion_rate" => 0,
        ),
        'data_all_time' => array(
            "date" => "2017-08-20",
            "paid_amount" => 50,
            "welth_order_paid_amount" => 50,
            "welth_order_paid_count" => 1,
            "welth_order_unpaid_count" => 0,
            "welth_order_completion_rate" => 1,
            "vip_order_paid_amount" => 0.00,
            "vip_order_paid_count" => 0,
            "vip_order_unpaid_count" => 0,
            "vip_order_completion_rate" => 0,
        ),
        'data_this_month' => array(
            "date" => "2017-08-20",
            "paid_amount" => 50,
            "welth_order_paid_amount" => 50,
            "welth_order_paid_count" => 1,
            "welth_order_unpaid_count" => 0,
            "welth_order_completion_rate" => 1,
            "vip_order_paid_amount" => 0.00,
            "vip_order_paid_count" => 0,
            "vip_order_unpaid_count" => 0,
            "vip_order_completion_rate" => 0,
        ),
        'data_member_yesterday' => array(
            "new_member_count" => 3,
            "male_count" => 1,
            "female_count" => 2,
            "subscribed_count" => 2,
            "subscribe_rate" => 0.67,
            "paid_count" => 3,
            "pay_rate" => 1,
        ),
        'data_member_this_month' => array(
            "new_member_count" => 3,
            "male_count" => 1,
            "female_count" => 2,
            "subscribed_count" => 2,
            "subscribe_rate" => 0.67,
            "paid_count" => 3,
            "pay_rate" => 1,
        ),
        'data_member_all_time' => array(
            "new_member_count" => 3,
            "male_count" => 1,
            "female_count" => 2,
            "subscribed_count" => 2,
            "subscribe_rate" => 0.67,
            "paid_count" => 3,
            "pay_rate" => 1,
        ),
        'data_member_daily_table' => array(
            array(
                "date" => "2017-08-21",
                "new_member_count" => 6,
                "subscribed_count" => 5,
                "paid_count" => 5,
                "male_count" => 50,
                "female_count" => 1,
            ),
            array(
                "date" => "2017-08-21",
                "new_member_count" => 6,
                "subscribed_count" => 5,
                "paid_count" => 5,
                "male_count" => 50,
                "female_count" => 1,
            ),
            array(
                "date" => "2017-08-21",
                "new_member_count" => 6,
                "subscribed_count" => 5,
                "paid_count" => 5,
                "male_count" => 50,
                "female_count" => 1,
            ),
            array(
                "date" => "2017-08-21",
                "new_member_count" => 6,
                "subscribed_count" => 5,
                "paid_count" => 5,
                "male_count" => 50,
                "female_count" => 1,
            ),
            array(
                "date" => "2017-08-21",
                "new_member_count" => 6,
                "subscribed_count" => 5,
                "paid_count" => 5,
                "male_count" => 50,
                "female_count" => 1,
            ),
        ),
        'daily_table' => array(
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
            array(
                "date" => "2017-08-21",
                "paid_amount" => 60,
                "welth_order_paid_amount" => 60,
                "welth_order_paid_user_count" => 5,
                "welth_order_avg_user_paid_amount" => 50,
                "welth_order_paid_count" => 1,
                "welth_order_unpaid_count" => 1,
                "welth_order_completion_rate" => 0.5,
                "vip_order_paid_amount" => 0.00,
                "vip_order_paid_user_count" => 3,
                "vip_order_avg_user_paid_amount" => 30,
                "vip_order_paid_count" => 0,
                "vip_order_unpaid_count" => 0,
                "vip_order_completion_rate" => 0,
            ),
        ),
    ),
);